### ISSUE TITLE
./bootstrap-dg.sh command failed in 'Linking CXX executable llvm-pta-compare'

### ISSUE THREAD

**Issue by Aiswarya-kk** [staticafi/sbt-instrumentation#40]
Please help me to solve this issue attached in the screenshot while executing the command   
 **./bootstrap-dg.sh**
![issue-sbt](https://user-images.githubusercontent.com/53484324/64143969-135b1880-ce30-11e9-934f-0419c301a3c4.png)

**Comment by mchalupa** [comment]
Your system is missing libz library (that's the `-lz` flag).

**Comment by Aiswarya-kk** [comment]
> Your system is missing libz library (that's the `-lz` flag).

Sir, How can I get that library file.

**Comment by mchalupa** [comment]
Install it with your package manager ;)

**Comment by Aiswarya-kk** [comment]
> Install it with your package manager ;)

Thank you. That issue is solved.But now I am facing this new error.
![sbt-error2](https://user-images.githubusercontent.com/53484324/64182452-e33e6480-ce85-11e9-8caf-90ead3625501.png)
