### ISSUE TITLE
ERROR: Linking instrumentation functions failed!

### ISSUE THREAD

**Issue by Aiswarya-kk** [staticafi/sbt-instrumentation#42]
Please help me to solve this issue.It shows **/bin/sh: 1: llvm-link: not found**
 and thus **ERROR: Linking instrumentation functions failed!**

![error-sbt5](https://user-images.githubusercontent.com/53484324/64229785-715b2f00-cf08-11e9-9eb3-b79b65330603.png)

**Comment by mchalupa** [comment]
`llvm-link` is a part of LLVM package (or build), so you must set-up the PATH variable to a directory with this binary.

**Comment by mchalupa** [comment]
sbt-instr can link the definitions itself, I changed the sbt-instr-c script to use this functionality. If you pull the changes, it should fix also your problem.

**Comment by Aiswarya-kk** [comment]
> `llvm-link` is a part of LLVM package (or build), so you must set-up the PATH variable to a directory with this binary.

Thank you sir. It works for me.

**Comment by mchalupa** [comment]
Great!
